### ISSUE TITLE
Error when running the `master` branch of simplesamlphp

### ISSUE THREAD

**Issue by sklarsa** [simplesamlphp/docker-simplesamlphp#3]
Per the instructions, I copied the simplesamlphp repo and ran docker-compose, but when I try to access the idp or sp, I get the following error...
```
$ docker logs docker-simplesamlphp_idp.tutorial.stack-dev.cirrusidentity.com_1
[Tue Oct 13 19:56:44 2020] 172.22.0.9:49084 [200]: / - Uncaught Exception: Unable to load Composer autoloader in /code/lib/_autoload.php:20
Stack trace:
#0 /code/www/_include.php(4): require_once()
#1 /code/www/index.php(3): require_once('/code/www/_incl...')
#2 {main}
  thrown in /code/lib/_autoload.php on line 20
```

**Comment by sklarsa** [comment]
Ah, it appears I needed to install the php dependencies in the simplesamlphp dir before running...
